### PR TITLE
Similar to winget, provide instructions for stable/beta/nightly for other package managers

### PR DESCRIPTION
**Pull request by vraravam**
Since we publish nightlies/beta/stable - we should probably provide instructions for installing any of them. The instructions for the `winget` package manager are already present on the website. This PR replicates the same for homebrew, scoop, etc

Note: I have tested only the homebrew steps. I would request others to test the other package managers and then approve this PR

### CODE REVIEW

**Comment by cino** [comment]
For the brew version, shouldn't that point to `brew cask` as it is a graphical application?

**Comment by vraravam** [comment]
> For the brew version, shouldn't that point to `brew cask` as it is a graphical application?

As long as there's no clash in names between formulae and casks, `brew install ferdium` will also work.

**Comment by Alphrag** [comment]
The choco package doesn't yet have the stable (the automatic updater didn't pick it up since a nightly got released before it ran that night), and we are considering if it's not worth only keeping the stable releases in there since it can be a bit complicated to have both because of the way choco updates are done. Do you think it is really interesting to provide stable in there too?

Another change will be Flatpak to add the info for the beta as soon as it will be ready.

**Comment by vraravam** [comment]
If its not there already, lets not wait for the flatpack betas.

For choco - please decide and update the PR

**Comment by Alphrag** [comment]
Sorry for the delay, I was waiting for the chocolatey stable package to be accepted.
For the others, `scoop` does not yet have a stable release, and `flatpak` will have the beta added at some point, so it is better to leave it out until it is done, but to merge this PR asap to have the `brew` and `choco` now correct.

**Pull request merged**
